apps:
  - name: fastapi
    script: /home/fastapi/venv/bin/uvicorn
    args: main:app --host 0.0.0.0 --port 8000
    interpreter: /home/fastapi/venv/bin/python3
    instances: 1
    log_date_format: 'YYYY-MM-DD HH:mm Z'
    merge_logs: true
    env_file: /home/fastapi/.env